### ISSUE TITLE
Mau Tanya

### ISSUE THREAD

**Issue by Tanaka9531** [alvarobherman/alvbot#1]
Ini Buat Termux Atau Laptop ?

**Comment by alvarobherman** [comment]
Termux, tapi blom dicoba dan masih dalam project wkwkwk :v

**Comment by Tanaka9531** [comment]
Ohh... Nais Btw Bagi Web Api Dong Aku Pemula Bang :)

**Comment by alvarobherman** [comment]
https://st4rz.herokuapp.com/
https://tobz-api.herokuapp.com/
https://scrap.terhambar.com/
https://arugaz.herokuapp.com/
https://docs-jojo.herokuapp.com/

Dalam pembuatan Bot ini, gw pake API ini semua :v karena gw kan masih pemula, wajar aja lah yah :v

**Comment by Tanaka9531** [comment]
> https://st4rz.herokuapp.com/
> https://tobz-api.herokuapp.com/
> https://scrap.terhambar.com/
> https://arugaz.herokuapp.com/
> https://docs-jojo.herokuapp.com/
> 
> Dalam pembuatan Bot ini, gw pake API ini semua :v karena gw kan masih pemula, wajar aja lah yah :v

sama :) thx
