### ISSUE TITLE
Minta Tolong

### ISSUE THREAD

**Issue by Tanaka9531** [alvarobherman/alvbot#3]
Bang Bisa Buatin Codingan Ini https://docs-jojo.herokuapp.com/api/alkitabsearch?q=Matius%207:7 ,https://docs-jojo.herokuapp.com/api/alkitab ,https://docs-jojo.herokuapp.com/api/renungan dan https://docs-jojo.herokuapp.com/api/mediafire?url=http://www.mediafire.com/file/vexl3vst7h8ydb3/python-3.8.6-amd64.exe/file
gak pls buat di pc bukan termux bang

**Comment by alvarobherman** [comment]
Alkitab :

case '!alkitab':
            const alkitab = await get.get(https://docs-jojo.herokuapp.com/api/alkitabsearch?q=${ayat}').json()
            client.reply(from, `Ayat : ${ayat}\n Isi : ${isi}\nLink : ${link}`, id)
            break

Random Ayat : 

case '!randomayat:
            const randomayat = await get.get(https://docs-jojo.herokuapp.com/api/alkitab').json()
            client.reply(from, `Ayat : ${ayat}\n Img : ${img}\nIsi : ${isi}\nLink : ${link}`, id)
            break

Renungan : 

case '!renungan:
            const renungan = await get.get(https://docs-jojo.herokuapp.com/api/renungan').json()
            client.reply(from, `Isi : ${isi}\nJudul : ${judul}\nPesan : ${pesan}`, id)
            break

Mediafire : 

case '!mediafire:
            const mediafire = await get.get(https://docs-jojo.herokuapp.com/api/mediafire?url=${link}').json()
            client.reply(from, `Detail  : ${detail}\nFileName : ${filename}`, id)
            break

Kalo salah maaf yah TwT
Maklumlah masih pemula :v

**Comment by Tanaka9531** [comment]
> Alkitab :
> 
> case '!alkitab':
> const alkitab = await get.get([https://docs-jojo.herokuapp.com/api/alkitabsearch?q=${ayat}').json(](https://docs-jojo.herokuapp.com/api/alkitabsearch?q=$%7Bayat%7D').json())
> client.reply(from, `Ayat : ${ayat}\n Isi : ${isi}\nLink : ${link}`, id)
> break
> 
> Random Ayat :
> 
> case '!randomayat:
> const randomayat = await get.get(https://docs-jojo.herokuapp.com/api/alkitab').json()
> client.reply(from, `Ayat : ${ayat}\n Img : ${img}\nIsi : ${isi}\nLink : ${link}`, id)
> break
> 
> Renungan :
> 
> case '!renungan:
> const renungan = await get.get(https://docs-jojo.herokuapp.com/api/renungan').json()
> client.reply(from, `Isi : ${isi}\nJudul : ${judul}\nPesan : ${pesan}`, id)
> break
> 
> Mediafire :
> 
> case '!mediafire:
> const mediafire = await get.get([https://docs-jojo.herokuapp.com/api/mediafire?url=${link}').json(](https://docs-jojo.herokuapp.com/api/mediafire?url=$%7Blink%7D').json())
> client.reply(from, `Detail : ${detail}\nFileName : ${filename}`, id)
> break
> 
> Kalo salah maaf yah TwT
> Maklumlah masih pemula :v

thx
